name: NeuralVoiceOS
options:
  bundleIdPrefix: com.minimax
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.0"

targets:
  NeuralVoiceOS:
    type: application
    platform: iOS
    sources:
      - path: NeuralVoiceOS
        excludes:
          - "**/*.plist"
    resources:
      - path: NeuralVoiceOS/Resources
      - path: NeuralVoiceOS/Assets.xcassets
    settings:
      base:
        INFOPLIST_FILE: NeuralVoiceOS/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.minimax.localaivoiceos
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: false
        ENABLE_BITCODE: false
        DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
    info:
      path: NeuralVoiceOS/Info.plist
      properties:
        CFBundleDisplayName: NeuralVoice OS
        NSMicrophoneUsageDescription: NeuralVoice OS needs access to your microphone to record and process voice audio.
        UIBackgroundModes:
          - audio
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities:
          - armv7
          - microphone
